### ISSUE TITLE
Adapting Rovernet for full 3D navigation

### ISSUE THREAD

**Issue by mhkabir** [dusty-nv/rovernet#1]
Hi Dusty,

Just opening this issue to contact you since I couldn't find any other way to reach out.

I would be interesting in implementing a Rovernet variant in full 3d, with some sort of occupancy mapping approach for global planning. Also, the vehicle would be full 6DoF system, so not constrained to the ground ;) Let me know if this sounds interesting. Maybe we could set up sort of a collaboration?

**Comment by dusty-nv** [comment]
Hello, sorry for the delay - it should be possible to implement 6DoF system by increasing the number of outputs of the network that estimates the Q-function.  Currently the outputs setup for ground rover correspond to [forward, backward, left, right].  Robots that have other controls can create additional output nodes, however it may take longer to train the more degrees of freedom there are to explore.

Here's my contact info if you'd like to discuss it further - dustinf@nvidia.com
I will also add this to the README.md and am open to further collaboration.

**Comment by mhkabir** [comment]
@dusty-nv Emailed you, thanks.
